const SpeakersList = {
	DurjoyDatta : {
		name: 'Durjoy Datta',
		subHeading: 'Novelist and Screen-Writer',
		imgLg: 'https://i.imgur.com/iy4hk3x.jpg',
		facebook : 'https://www.facebook.com/durjoydatta1/',
		instagram: 'https://www.instagram.com/durjoydatta/?hl=en',
		twitter: 'https://twitter.com/durjoydatta',
		desc: 'A DTU student who transformed himself into a bestselling novelist with his fantabulous writing skills. The Young Achiever who chose to pursue his passion of writing after serving at Siemens and American Express. He has released a series of novels which has brought a cult and has struck a cord with the youth of India. With his novels, short stories and screenwriting, he has undoubtedly manifested his adaptability in writing. Of Course you know this man!. The youth icon, Durjoy Datta.',
	},
	YuvrajThakur : {
		name: 'Yuvraj Thakur',
		subHeading: 'Actor,Writer and Fitness Enthusiat',
		imgLg: 'https://i.imgur.com/PDRNukg.jpg',
		facebook : 'https://www.facebook.com/passionateyuvraj/',
		instagram: 'https://www.instagram.com/yuv_thehuman/?hl=en',
		twitter: 'https://twitter.com/thakuryuvi?lang=en',
		desc: ' He is a young man with high demeanour and a plethora of dexterities to his credit. A perceptive observer with an impassioned sense of judgement, he is an intuitive learner of life itself. An actor and model by profession, he fits in yet stands out from the troupe. Inspired by the intricacies of nature and existence, he is an animated and striking poet. Passionate about his strength and well-being, he is also a fitness enthusiast. He is a youthful and personable being with nothing yet everything. Presenting the high-spirited individualist.',
	},
	DrMSkhuroo: {
		name: 'Dr. MS Khuroo',
		subHeading: 'Discoverer of Hepatitis-E',
		imgLg: 'https://i.imgur.com/vsb8scp.jpg',
		facebook : 'https://www.facebook.com/drkhuroo/',
		instagram: '',
		twitter: '',
		desc: 'A Gastroenterogist by profession, accredited with discovering Hepaptitis E, treatment of Hepatic Hydatid cysts , a drug treatment to bleeding peptic ulcer, saving millions of lives worldwide. A household name in Kashmir due to his intrumental role in discovering major health problem of Hepatobiliary and pancreatic ascarisis and enlightening billions of lives due to his invariable efforts in providing his valuable assistance to the people of Kashmir and the medical fraternity in the form of his innumerable research works. He is Dr. Mohammad Khuroo, a man in no need of an introduction.',
	},
	ImamSiddique : {
		name: 'Imam A Siddique',
		subHeading: 'Style Icon',
		imgLg: 'https://i.imgur.com/PgRyA2k.jpg',
		facebook : 'https://www.facebook.com/Spotlight.ImamSiddique/',
		instagram: 'https://www.instagram.com/imam_a_siddique/',
		twitter: 'https://twitter.com/Imam_A_Siddique',
		desc: 'A remarkable image consultant and casting director by calling and a maestro of prolific originality; he is the very definition of exuberance. He laid the foundation of his career at a very young age and embarked on his journey as a fashion model. Shaped by his zeal for creativity and innovation, he is also a passionate poet, dancer and a photographer who is accredited with the launch of many fresh faces to the industry. Always on the lookout for ingenuity, he inspires the youth of today to hold onto one’s passion. Presenting the vivacious all-rounder',
	},
	RamPunyani : {
		name: 'Ram Punyani',
		subHeading: 'Social Activist',
		imgLg: 'https://i.imgur.com/vsb8scp.jpg',
		facebook : 'https://www.facebook.com/ram.puniyani',
		instagram: 'https://twitter.com/rpuni?lang=en',
		twitter: 'https://twitter.com/rpuni?lang=en',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
	ShahFaesal : {
		name: 'Shah Faesal',
		subHeading: 'First IAS Topper from J&K',
		imgLg: 'https://i.imgur.com/yQX4tU0.jpg',
		facebook : 'https://www.facebook.com/shah.faesal.3',
		instagram: '',
		twitter: 'hhttps://twitter.com/shahfaesal?lang=en',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
	AnkurWarikoo : {
		name: 'Ankur Warikoo',
		subHeading: 'CEO and Founder nearbuy.com',
		imgLg: 'https://i.imgur.com/wn3U7j0.jpg',
		facebook : 'https://www.facebook.com/awarikoo/',
		instagram: 'ttps://www.instagram.com/warikoos/?hl=en',
		twitter: 'https://twitter.com/warikoo',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
	BabarAfsal : {
		name: 'Babar Afsal',
		subHeading: 'Hacker turned Shepard turend Entrepreneur',
		imgLg: 'https://i.imgur.com/IHJ3YCE.jpg',
		facebook : 'https://www.facebook.com/kingoftimes?ref=br_rs',
		instagram: 'https://www.instagram.com/afzal.babar/',
		twitter: 'https://twitter.com/babarafzal?lang=en',
		desc: 'The man who quitted his corporate career and silicon valley lifestyle to become a shepherd and protect pashmina. He aimed to find an economic solution for the communities that are linked to pashmina industries in India. His story is a classic example of how success without meaning is not rewarding. He gave up everything to dedicate himself to a cause he believes in : Preserving the pashmina ecosystem of Kashmir.',
	},
	SavitaBhanWakhlu : {
		name: 'Savita Bhan Wakhlu',
		subHeading: 'Managing Director Jagriti Communications',
		imgLg: 'https://i.imgur.com/WOo9Cej.jpg',
		facebook : 'https://www.facebook.com/savita.wakhlu?ref=br_rs',
		instagram: '',
		twitter: 'https://twitter.com/swakhlu',
		desc: 'Managing Director of Jagriti Communications, which expertises and focuses exclusively on Indivisual and Organisational Training and development. Also an Engineer,a certified personal and executive coach, a certified cross-cultural trainer and consultant and a certified EQ resource from FEIL, India. She has been credited with  a lot of work in personal effectiveness, management and leadership.she has co-authored a book  "Navigating The Maze" speak loads about living our lives productively, joyfully, and in peace and harmony in whatever role one choses to be. Also, an Alumni of NIT Srinagar, we present Savita Bhan Wakhlu.',
	},
	SoveshMohapatra : {
		name: 'Sovesh Mohapatra',
		subHeading: 'Junior Scientist',
		imgLg: 'https://i.imgur.com/jQHQhOJ.jpg',
		facebook : 'https://www.facebook.com/SoveshM?ref=br_rs',
		instagram: '',
		twitter: 'https://twitter.com/MohapatraSovesh',
		desc: 'A high school lad from a small town in Odisha and a child prodigy who is a recipient of National Child Award.He was the youngest speaker to address the delegates at Indian Science Congress 2016. He has also represented his home state at National Childrens Science Congress in 2015.He started his research on Power Generation in Grade-4, a rare thing of its kind and as a result of which he was called upon by Oxford University for research with Dr. Neil Aston, a noted scientist.After 5 years of sheer research in Oxford University, he developed a project on Domestic Water Power Plant form Multiple Uses, using his experimental and theoretical savvy.Apart from this, he has numerous awards and literature publications in his credit.He is also a social worker, being the founder and co-founder of various NGOs.He also holds a strong field in music and instrumentation and equally skilled with them.',
	},
};

export default SpeakersList;
