const SpeakersList = {
	DurjoyDatta : {
		name: 'Durjoy Datta',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/iy4hk3x.jpg',
		facebook : 'https://www.facebook.com/durjoydatta1/',
		instagram: 'https://www.instagram.com/durjoydatta/?hl=en',
		twitter: 'https://twitter.com/durjoydatta',
		desc: 'This man is an impeccable writer who has authored numerous best selling novels and carved a niche for himself as one of the most prolific writer of contemporary time.He also has been the screenwriter of many popular TV shows.He has been awarded Young Achiever by Times of India.Of course you know this man! The youth icon : Durjoy Datta',
	},
	YuvrajThakur : {
		name: 'Yuvraj Thakur',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/PDRNukg.jpg',
		facebook : 'https://www.facebook.com/passionateyuvraj/',
		instagram: 'https://www.instagram.com/yuv_thehuman/?hl=en',
		twitter: 'https://twitter.com/thakuryuvi?lang=en',
		desc: ' A man who is the student of life, a shrewd observer with an astute sense of understanding the nature and a maverick who writes, speaks and acts.is an actor by profession, a ruminative writer by passion and a human with nothing yet everything.He is no other than Yuvraj Thakur.',
	},
	DrMSkhuroo: {
		name: 'Dr. MS Khuroo',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/vsb8scp.jpg',
		facebook : 'https://www.facebook.com/drkhuroo/',
		instagram: '',
		twitter: '',
		desc: 'A Gastroenterogist by profession, accredited with discovering Hepaptitis E, treatment of Hepatic Hydatid cysts , a drug treatment to bleeding peptic ulcer, saving millions of lives worldwide. A household name in Kashmir due to his intrumental role in discovering major health problem of Hepatobiliary and pancreatic ascarisis and enlightening billions of lives due to his invariable efforts in providing his valuable assistance to the people of Kashmir and the medical fraternity in the form of his innumerable research works. He is Dr. Mohammad Khuroo, a man in no need of an introduction.',
	},
	ImamSiddique : {
		name: 'Imam A Siddique',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/PgRyA2k.jpg',
		facebook : 'https://www.facebook.com/Spotlight.ImamSiddique/',
		instagram: 'https://www.instagram.com/imam_a_siddique/',
		twitter: 'https://twitter.com/Imam_A_Siddique',
		desc: 'Imam Siddiqui: A casting director by profession and an artist by passion who also stimulates art in every form. Accredited with engaging multitudinous models, photographers, designers,stylists and editors into the mainstream. Always inspiring to hold on to ones passion by providing the much needed canvas. Presenting the ultimate allrounder, Imamieddienne Afroze Emir Siddiqui a.k.a. Imam Siddiqui.',
	},
	RamPunyani : {
		name: 'Ram Punyani',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/vsb8scp.jpg',
		facebook : 'https://www.facebook.com/ram.puniyani',
		instagram: 'https://twitter.com/rpuni?lang=en',
		twitter: 'https://twitter.com/rpuni?lang=en',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
	ShahFaesal : {
		name: 'Shah Faesal',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/yQX4tU0.jpg',
		facebook : 'https://www.facebook.com/ram.puniyani',
		instagram: 'https://twitter.com/rpuni?lang=en',
		twitter: 'https://twitter.com/rpuni?lang=en',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
	AnkurWarikoo : {
		name: 'Ankur Warikoo',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/wn3U7j0.jpg',
		facebook : 'https://www.facebook.com/ram.puniyani',
		instagram: 'https://twitter.com/rpuni?lang=en',
		twitter: 'https://twitter.com/rpuni?lang=en',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
	BabarAfsal : {
		name: 'Babar Afsal',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/IHJ3YCE.jpg',
		facebook : 'https://www.facebook.com/ram.puniyani',
		instagram: 'https://twitter.com/rpuni?lang=en',
		twitter: 'https://twitter.com/rpuni?lang=en',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
	SavitaBhanWakhlu : {
		name: 'Savita Bhan Wakhlu',
		subHeading: 'Great Person',
		imgLg: 'https://i.imgur.com/WOo9Cej.jpg',
		facebook : 'https://www.facebook.com/ram.puniyani',
		instagram: 'https://twitter.com/rpuni?lang=en',
		twitter: 'https://twitter.com/rpuni?lang=en',
		desc: 'A former doctor and a biomedical engineering professor, who took voluntary retirement to dedicate himself to the noble cause of communal harmony in India.He has been putting his mind, body and soul in advocating human rights, promoting secularism, battling the extremism and constantly confronting the rising tide of religious fundamentalism in India.Today, he has been working towards engineering a secular and a plural society, as envisaged by our constitution. He is the voice of voiceless in the society.',
	},
};

export default SpeakersList;
